### ISSUE TITLE
Multi Husky Robots don't move when writing in their cmd_vel topic

### ISSUE THREAD

**Issue by Sdehnavi** [husky/husky#104]
Hi,

I am using husky_gazebo package for simulating multi husky robots by launching "multi_husky_playpen.launch". The simulation is running and the environment and all the topics are created but noting happens when I write into /husky_velocity_controller/cmd_vel topic of each robot.

**Comment by shehancaldera** [comment]
You need to publish to the topic that starts with the namespace i.e. h1/husky_velocity_controller/cmd_vel Check this video for some clarification : https://www.youtube.com/watch?v=mFTkN5v4Jzc
