### ISSUE TITLE
Husky gmapping produces bad map in gazebo

### ISSUE THREAD

**Issue by erinline** [husky/husky#107]
The husky appears to have bad position estimation while doing SLAM. I am running on ROS melodic, but everything else works fine. Doing the husky navigation tutorials. Are there parameters that need to be changed? I am including a picture of the map that results. It is not smooth, i.e. the husky can pass through an area and not label it clear, and it is improperly aligned.
![husky_map](https://user-images.githubusercontent.com/18197093/54094623-aaab4b80-4378-11e9-88bc-cba94b488d21.png)

Then I drove it into the wall for a while to see if it could tell it's not moving, and it cannot. It just keeps adding the wall in new places, as shown in this pic.
![husky_map2](https://user-images.githubusercontent.com/18197093/54094640-cadb0a80-4378-11e9-9bbe-bc188fd7ee19.png)

What can I do to get better maps?

**Comment by tonybaltovski** [comment]
Here is a starting point: https://answers.ros.org/question/269280/how-to-make-better-maps-using-gmapping/

In general, you need to tune the gmapping parameters for your use case.
