### ISSUE TITLE
How does the /cmd_vel topic drive the husky exactly?

### ISSUE THREAD

**Issue by vinbo** [husky/husky#114]
Hi, I'm new to the ROS structure. I see from the rqt_graph that the motion of the husky by exotic control is from the subscription of the topic /cmd_vel, right? Then my question is, how can i see the dynamic equations which describes the relation from /cmd to the real motion of husky? in which file can I see it?  which function subsribes the topic /cmd_vel? Thank you.
-------update line----
I found this file https://bitbucket.org/osrf/simulator_gazebo/src/default/gazebo/src/gazebo_ros_api_plugin.cpp, which indicates that the dynamics are solved by ode solver. so the remaining question is, how does the /cmd_vel topic becomes the force/torque applied to the robot? where  can I see the controller?

**Comment by tonybaltovski** [comment]
The  [diff_drive_controller](http://wiki.ros.org/diff_drive_controller) is used for the Husky.  Since this is not an issue with this repo, I ask that you ask your question on [ROS Answers](https://answers.ros.org/questions/) if the link above does not clarify it for you.
