### ISSUE TITLE
issue with service husky-core start ??

### ISSUE THREAD

**Issue by Abduoit** [husky/husky#119]
Hello 

I upgraded Husky image from indigo to kinetic, everything seems fine, light gets green and the joystick works. But there's issue with husky-core start.

Any suggestions please ??

```
administrator@administrator:~$ sudo service husky-core start
Failed to start husky-core.service: Unit husky-core.service not found.
```

**Comment by tonybaltovski** [comment]
@Abduoit this was changed in Kinetic since Xenial uses systemd and not upstart.  Use: `sudo systemctl start ros`.
