### ISSUE TITLE
Driving husky in gazebo environment

### ISSUE THREAD

**Issue by ZakariaChekakta** [husky/husky#124]
Hi, 
I am testing the husky robot using Gazebo 9 and ROS melodic when I move the robot forward or backward, it working properly, but turning the robot to the left or the right, I noticed a strange behavior in the robot movement, Is that behavior normal or there is a bug needs to be fixed?

![husky_sim_test](https://user-images.githubusercontent.com/12950797/75216479-77efa280-57d7-11ea-953b-b8253594b3fe.gif)

**Comment by h3ct0r** [comment]
I'm having the same problem (see video [https://youtu.be/yKhHC9QsZZY](ur)) This is also described in other issues such as [https://github.com/husky/husky/issues/120](url) and [https://github.com/husky/husky/issues/105](url). But so far the Clearpath team has not responded to these issues.

@tonybaltovski Hi! Can you take a look at this, please? It seems that there are multiple people reporting this.

**Comment by nmarticorena** [comment]
Hi, someone manage to solve this issue? 

I already tried the comments in the other issues but the problem persists.

Any help or comment would be really appreciated.
