### ISSUE TITLE
Noetic Release

### ISSUE THREAD

**Issue by archielee** [husky/husky#151]
Hi, just wondering when we can expect a release for Noetic/20.04. Thanks!

**Comment by civerachb-cpr** [comment]
Unfortunately we can't give you a hard timeline for when we'll get the Noetic release ready.  It's in our pipeline, and we hope to have it out Q1 of 2021.  Husky and Jackal are likely going to be the first two platforms to get Noetic support.

**Comment by archielee** [comment]
Awesome, thanks for the prompt response. Closing this issue.
