### ISSUE TITLE
husky_bringup not building

### ISSUE THREAD

**Issue by elleszabo** [husky/husky#156]
System: Ubuntu 18.04
Distro: ROS melodic
I simply cloned this repo and catkin built

These are my errors in the husky_bringup package:

`Errors     << moveit_core:make /home/elle/catkin_ws/logs/moveit_core/build.make.001.log             
/home/elle/catkin_ws/src/moveit/moveit_core/robot_state/src/conversions.cpp: In function ‘void moveit::core::{anonymous}::_attachedBodyToMsg(const moveit::core::AttachedBody&, moveit_msgs::AttachedCollisionObject&)’:
/home/elle/catkin_ws/src/moveit/moveit_core/robot_state/src/conversions.cpp:220:14: error: ‘moveit_msgs::AttachedCollisionObject_<std::allocator<void> >::_object_type {aka struct moveit_msgs::CollisionObject_<std::allocator<void> >}’ has no member named ‘subframe_names’
   aco.object.subframe_names.clear();
              ^~~~~~~~~~~~~~
/home/elle/catkin_ws/src/moveit/moveit_core/robot_state/src/conversions.cpp:221:14: error: ‘moveit_msgs::AttachedCollisionObject_<std::allocator<void> >::_object_type {aka struct moveit_msgs::CollisionObject_<std::allocator<void> >}’ has no member named ‘subframe_poses’; did you mean ‘plane_poses’?
   aco.object.subframe_poses.clear();
              ^~~~~~~~~~~~~~
              plane_poses
/home/elle/catkin_ws/src/moveit/moveit_core/robot_state/src/conversions.cpp:224:16: error: ‘moveit_msgs::AttachedCollisionObject_<std::allocator<void> >::_object_type {aka struct moveit_msgs::CollisionObject_<std::allocator<void> >}’ has no member named ‘subframe_names’
     aco.object.subframe_names.push_back(frame_pair.first);
                ^~~~~~~~~~~~~~
/home/elle/catkin_ws/src/moveit/moveit_core/robot_state/src/conversions.cpp:227:16: error: ‘moveit_msgs::AttachedCollisionObject_<std::allocator<void> >::_object_type {aka struct moveit_msgs::CollisionObject_<std::allocator<void> >}’ has no member named ‘subframe_poses’; did you mean ‘plane_poses’?
     aco.object.subframe_poses.push_back(pose);
                ^~~~~~~~~~~~~~
                plane_poses
/home/elle/catkin_ws/src/moveit/moveit_core/robot_state/src/conversions.cpp: In function ‘void moveit::core::{anonymous}::_msgToAttachedBody(const moveit::core::Transforms*, const AttachedCollisionObject&, moveit::core::RobotState&)’:
/home/elle/catkin_ws/src/moveit/moveit_core/robot_state/src/conversions.cpp:256:22: error: ‘const _object_type {aka const struct moveit_msgs::CollisionObject_<std::allocator<void> >}’ has no member named ‘subframe_poses’; did you mean ‘plane_poses’?
       if (aco.object.subframe_poses.size() != aco.object.subframe_names.size())
                      ^~~~~~~~~~~~~~
                      plane_poses
/home/elle/catkin_ws/src/moveit/moveit_core/robot_state/src/conversions.cpp:256:58: error: ‘const _object_type {aka const struct moveit_msgs::CollisionObject_<std::allocator<void> >}’ has no member named ‘subframe_names’
       if (aco.object.subframe_poses.size() != aco.object.subframe_names.size())
                                                          ^~~~~~~~~~~~~~
/home/elle/catkin_ws/src/moveit/moveit_core/robot_state/src/conversions.cpp:304:48: error: ‘const _object_type {aka const struct moveit_msgs::CollisionObject_<std::allocator<void> >}’ has no member named ‘subframe_poses’; did you mean ‘plane_poses’?
         for (std::size_t i = 0; i < aco.object.subframe_poses.size(); ++i)
                                                ^~~~~~~~~~~~~~
                                                plane_poses
/home/elle/catkin_ws/src/moveit/moveit_core/robot_state/src/conversions.cpp:307:35: error: ‘const _object_type {aka const struct moveit_msgs::CollisionObject_<std::allocator<void> >}’ has no member named ‘subframe_poses’; did you mean ‘plane_poses’?
           tf2::fromMsg(aco.object.subframe_poses[i], p);
                                   ^~~~~~~~~~~~~~
                                   plane_poses
/home/elle/catkin_ws/src/moveit/moveit_core/robot_state/src/conversions.cpp:308:41: error: ‘const _object_type {aka const struct moveit_msgs::CollisionObject_<std::allocator<void> >}’ has no member named ‘subframe_names’
           std::string name = aco.object.subframe_names[i];
                                         ^~~~~~~~~~~~~~
make[2]: *** [robot_state/CMakeFiles/moveit_robot_state.dir/src/conversions.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [robot_state/CMakeFiles/moveit_robot_state.dir/all] Error 2
make: *** [all] Error 2
cd /home/elle/catkin_ws/build/moveit_core; catkin build --get-env moveit_core | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
`

What is going on?

**Comment by civerachb-cpr** [comment]
I'm assuming that since you closed this ticket you've found the solution yourself?
