### ISSUE TITLE
Husky spawns in simulation with base_link gravtity disabled

### ISSUE THREAD

**Issue by edncke** [husky/husky#181]
- OS: Ubuntu 20.04
- ROS Distro: Noetic
- Package Version: 0.5.0
- Simulation  

If I start the Husky-playpen simulation without the laser enabled everything works as expected.  
`roslaunch husky_gazebo husky_playpen.launch laser_enabled:=false`  
   
![screenshot_2021-08-30 17-55-11](https://user-images.githubusercontent.com/65857850/131370890-c32b287f-17fa-43a1-aec8-d29499b7f1fe.png)  
But if I enable the laser (or realsense) the Husky spawns with the gravity of the base_link disabled.  
`roslaunch husky_gazebo husky_playpen.launch laser_enabled:=true`  
   
![screenshot_2021-08-30 17-59-42](https://user-images.githubusercontent.com/65857850/131370934-ba7df3a7-eaa7-4804-9bad-8ccd35fe84b3.png)  

This is quite unfortunate if I want to launch the Husky with an UR5 + laser as the Husky just tips over from the weight of the arm. I can enable the gravity afterwards in gazebo but I can't find a way to spawn it with gravity set to true.  
I limited the setup to Husky + laser to make sure the bug does not come from any other package installed. To reproduce this I used only the newest Package (0.5.0) available here with the commands mentioned above.  
Any help would be much appreciated.

**Comment by nsch0e** [comment]
your issue seems to arise from the LMS1xx package. You can just delete this line to solve the issue:

https://github.com/clearpathrobotics/LMS1xx/blob/d80907e539d72a373002e9d68e4b982eb4b6d7ce/urdf/sick_lms1xx.urdf.xacro#L58
