### ISSUE TITLE
unable to calibrate the Magnetometer

### ISSUE THREAD

**Issue by adamanov** [husky/husky#182]
Hello, 
I was following the[ husky_bringup/Tutorial ](http://wiki.ros.org/husky_bringup/Tutorials/Install%20Husky%20Software)in order to calibrate our husky robot. 
However, during executing `rosrun husky_bringup calibrate_compass` , the robot start doing calibration but after that it end up wtih error 

``` 
administrator@RoboLabHusky:~$ rosrun husky_bringup calibrate_compass
Started rosbag record, duration 60 seconds, pid [2796]
Started motion commands, pid [2797]
[ INFO] [1635176570.765422809]: Subscribing to /imu/data
[ INFO] [1635176570.777846830]: Subscribing to /imu/mag
[ INFO] [1635176570.786708006]: Subscribing to /tf
[ INFO] [1635176570.814249172]: Recording to '/tmp/calibrate_compass.503v/imu_record.bag'.
Test underway.
Time remaining: 0   
Shutting down motion command publisher.
Waiting for rosbag to shut down.
Computing magnetic calibration.
Unable to compute calibration from recorded bag.
Output in /tmp/compute_output.log
administrator@RoboLabHusky:~$ cat /tmp/compute_output.log
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/husky_bringup/compute_calibration", line 42, in <module>
    vecs.append((float(msg.vector.x), float(msg.vector.y), float(msg.vector.z)))
AttributeError: '_sensor_msgs__MagneticField' object has no attribute 'vector
```

we have imu um7 on the robot

**Comment by civerachb-cpr** [comment]
Thanks for letting us know about this bug!  We'll look into it asap.
At first glance it looks like it's simply a missed change in the MagneticField message format.  The `vector` field appears to be called `magnetic_field` in Melodic.
Can you please try editing this line https://github.com/husky/husky/blob/92fe8eaadb65a8a2473f9f2e36009563496548a5/husky_bringup/scripts/compute_calibration#L42 to the following:

```
vecs.append((float(msg.magnetic_field.x), float(msg.magnetic_field.y), float(msg.magnetic_field.z)))
```

**Comment by adamanov** [comment]
> Thanks for letting us know about this bug! We'll look into it asap. At first glance it looks like it's simply a missed change in the MagneticField message format. The `vector` field appears to be called `magnetic_field` in Melodic. Can you please try editing this line
> 
> https://github.com/husky/husky/blob/92fe8eaadb65a8a2473f9f2e36009563496548a5/husky_bringup/scripts/compute_calibration#L42
> to the following:
> 
> ```
> vecs.append((float(msg.magnetic_field.x), float(msg.magnetic_field.y), float(msg.magnetic_field.z)))
> ```

Thanks for quick response. I changed the line and It worked right now.
