### ISSUE TITLE
Is it possible to use the voltage mode to control the robot in simulation?

### ISSUE THREAD

**Issue by alhaddad-m** [husky/husky#190]
Greetings! I have two questions related to the voltage mode.
1- I need to test the voltage mode to control the robot in simulation instead of the default **velocity mode**. I have read the this (voltage) mode is for hardware. Does that mean i cannot test it in simulation or there is another way?
2- When i change the control model into **voltage mode**.  What does the topic for publishing the command look like? I means is it still **cmd_vel** or it will be another topic and what is it?

Thanks in advance.

**Comment by tonybaltovski** [comment]
It can only be controlled using `cmd_vel`.
