### ISSUE TITLE
ROS2 Support

### ISSUE THREAD

**Issue by shrijitsingh99** [husky/husky#199]
What is the current timeline for releasing ROS2 support? Is the current galactic branch in a somewhat stable and usable state?

**Comment by jeferal** [comment]
Is it currently possible to run the husky robot with the foxy-devel branch (both the real one and the gazebo simualtion)?

**Comment by tonybaltovski** [comment]
@shrijitsingh99 The galactic branch should be stable.  However, support for galactic will be limited since it is not a LTS.

**Comment by tonybaltovski** [comment]
@jeferrandiz98 Yes both are possible.
