### ISSUE TITLE
Ros2_control crashes in Foxy Gazebo launch

### ISSUE THREAD

**Issue by alpylmz** [husky/husky#219]
**Please provide the following information:**
 - OS: Ubuntu 20.04
 - ROS Distro: Foxy
 - Built from source or installed: Foxy is installed, Husky is built from source
 - Package version: e18bdb61e990378390ce5e9df14ed43316313733
 - Real hardware or simulation: Simulation

 **Expected behaviour**
 When gazebo_launch.py is launched, Gazebo should open, Husky should be spawned without any errors.

 **Actual behaviour**
 Gazebo and Husky opens and can be controlled, but while opening ros2_control_node crashes.

**To Reproduce**
Provide the steps to reproduce:
1. run ros2 launch husky_gazebo gazebo_launch.py
2. error:
 [INFO] [launch]: All log files can be found below /home/alp/.ros/log/2022-03-31-12-04-51-037625-alp-kae-38110
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [robot_state_publisher-1]: process started with pid [38115]
[INFO] [ros2_control_node-2]: process started with pid [38117]
[INFO] [spawner.py-3]: process started with pid [38119]
[INFO] [gzserver-4]: process started with pid [38121]
[INFO] [gzclient-5]: process started with pid [38123]
[INFO] [spawn_entity.py-6]: process started with pid [38125]
[robot_state_publisher-1] Parsing robot urdf xml string.
[robot_state_publisher-1] Link base_footprint had 0 children
[robot_state_publisher-1] Link front_bumper_link had 0 children
[robot_state_publisher-1] Link front_left_wheel had 0 children
[robot_state_publisher-1] Link front_right_wheel had 0 children
[robot_state_publisher-1] Link imu_link had 0 children
[robot_state_publisher-1] Link inertial_link had 0 children
[robot_state_publisher-1] Link rear_bumper_link had 0 children
[robot_state_publisher-1] Link rear_left_wheel had 0 children
[robot_state_publisher-1] Link rear_right_wheel had 0 children
[robot_state_publisher-1] Link top_chassis_link had 0 children
[robot_state_publisher-1] Link top_plate_link had 2 children
[robot_state_publisher-1] Link top_plate_front_link had 0 children
[robot_state_publisher-1] Link top_plate_rear_link had 0 children
[robot_state_publisher-1] Link user_rail_link had 0 children
[robot_state_publisher-1] [INFO] [1648717491.395105190] [robot_state_publisher]: got segment base_footprint
[ros2_control_node-2] terminate called after throwing an instance of 'pluginlib::LibraryLoadException'
[ros2_control_node-2]   what():  According to the loaded plugin descriptions the class gazebo_ros2_control/GazeboSystem with base class type hardware_interface::SystemInterface does not exist. Declared types are  fake_components/GenericSystem husky_base/HuskyHardware test_hardware_components/TestSystemCommandModes test_hardware_components/TestTwoJointSystem test_system
[robot_state_publisher-1] [INFO] [1648717491.395216377] [robot_state_publisher]: got segment base_link
[robot_state_publisher-1] [INFO] [1648717491.395232021] [robot_state_publisher]: got segment front_bumper_link
[robot_state_publisher-1] [INFO] [1648717491.395242497] [robot_state_publisher]: got segment front_left_wheel
[robot_state_publisher-1] [INFO] [1648717491.395252135] [robot_state_publisher]: got segment front_right_wheel
[robot_state_publisher-1] [INFO] [1648717491.395263449] [robot_state_publisher]: got segment imu_link
[robot_state_publisher-1] [INFO] [1648717491.395273507] [robot_state_publisher]: got segment inertial_link
[robot_state_publisher-1] [INFO] [1648717491.395283633] [robot_state_publisher]: got segment rear_bumper_link
[robot_state_publisher-1] [INFO] [1648717491.395293970] [robot_state_publisher]: got segment rear_left_wheel
[robot_state_publisher-1] [INFO] [1648717491.395305005] [robot_state_publisher]: got segment rear_right_wheel
[robot_state_publisher-1] [INFO] [1648717491.395316040] [robot_state_publisher]: got segment top_chassis_link
[robot_state_publisher-1] [INFO] [1648717491.395326795] [robot_state_publisher]: got segment top_plate_front_link
[robot_state_publisher-1] [INFO] [1648717491.395336293] [robot_state_publisher]: got segment top_plate_link
[robot_state_publisher-1] [INFO] [1648717491.395345862] [robot_state_publisher]: got segment top_plate_rear_link
[robot_state_publisher-1] [INFO] [1648717491.395355290] [robot_state_publisher]: got segment user_rail_link
[spawner.py-3] [INFO] [1648717491.575910287] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[ERROR] [ros2_control_node-2]: process has died [pid 38117, exit code -6, cmd '/opt/ros/foxy/lib/controller_manager/ros2_control_node --ros-args --params-file /tmp/launch_params_bu0m9b20 --params-file /home/alp/husky_ws/install/husky_control/share/husky_control/config/control.yaml'].
[spawn_entity.py-6] [INFO] [1648717491.766196074] [spawn_husky]: Spawn Entity started
[spawn_entity.py-6] [INFO] [1648717491.766578243] [spawn_husky]: Loading entity published on topic robot_description
[spawn_entity.py-6] [INFO] [1648717491.768115091] [spawn_husky]: Waiting for entity xml on robot_description
[spawn_entity.py-6] [INFO] [1648717491.780825013] [spawn_husky]: Waiting for service /spawn_entity, timeout = 30
[spawn_entity.py-6] [INFO] [1648717491.781150681] [spawn_husky]: Waiting for service /spawn_entity
[spawner.py-3] [INFO] [1648717491.783302757] [spawner_joint_state_broadcaster]: Controller already loaded, skipping load_controller
[spawner.py-3] [INFO] [1648717491.785992748] [spawner_joint_state_broadcaster]: Failed to configure controller
[ERROR] [spawner.py-3]: process has died [pid 38119, exit code 1, cmd '/opt/ros/foxy/lib/controller_manager/spawner.py joint_state_broadcaster -c /controller_manager --ros-args'].
[INFO] [spawner.py-7]: process started with pid [38212]
[spawner.py-7] [INFO] [1648717492.010428207] [spawner_husky_velocity_controller]: Waiting for /controller_manager services
[spawn_entity.py-6] [INFO] [1648717492.036147946] [spawn_husky]: Calling service /spawn_entity
[spawn_entity.py-6] [INFO] [1648717492.056025496] [spawn_husky]: Spawn status: Entity [husky] already exists.
[spawn_entity.py-6] [ERROR] [1648717492.056439862] [spawn_husky]: Spawn service failed. Exiting.
[ERROR] [spawn_entity.py-6]: process has died [pid 38125, exit code 1, cmd '/opt/ros/foxy/lib/gazebo_ros/spawn_entity.py -entity husky -topic robot_description --ros-args -r __node:=spawn_husky'].
[ERROR] [spawner.py-7]: process has died [pid 38212, exit code 1, cmd '/opt/ros/foxy/lib/controller_manager/spawner.py husky_velocity_controller -c /controller_manager --ros-args'].
[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[robot_state_publisher-1] [INFO] [1648717503.800700081] [rclcpp]: signal_handler(signal_value=2)
[INFO] [robot_state_publisher-1]: process has finished cleanly [pid 38115]
[INFO] [gzserver-4]: process has finished cleanly [pid 38121]
[INFO] [gzclient-5]: process has finished cleanly [pid 38123]

**Other notes**
As far as I understand, this does not affect the working of Husky, but for my use case I need to understand why ros2_control_node crashes.

**Comment by tonybaltovski** [comment]
Hi, `ros2_control_node` isn't need for the simulation and was removed.  Thank you for bringing this up.
