### ISSUE TITLE
ROS2 Foxy Nav | Odom not using sim time

### ISSUE THREAD

**Issue by AngeLoGa** [husky/husky#240]
Greetings, I'm trying to simulate a husky in ROS2 Foxy. I recently started learning ROS and my first challenge was to set up a husky in a greenhouse and make it navigate autonomously.
I already changed the urdf so I added some lidars, and other sensors, and the world which in my case is a greenhouse. The launch that I'm working with is husky_playpen_launch.py, as the most tutorials says.

The problem comes when I try to use the package slam_toolbox, in order to use autonomous navigation. This message is published continuously in the terminal:

`[async_slam_toolbox_node-1] [INFO] [1655883679.453922940] [slam_toolbox]: Message Filter dropping message: frame 'ouster_link' at time 1363.150 for reason 'Unknown'`

It keeps saying that the message is being filtered, and couldn't make a map. Also, in RVIZ, it appears that the map doesn't have a tf from /map to /base_link

Trying to solve the problem, I saw that my odom frame is currently running in real time, and not in simulation time, as the base_link and the others do. If I launch `ros2 run tf2_tools view_frames.py` I can see in the tree that there's a connection between map, odom, and base_link, but as I said, I think the problem is in the time that odom is using.

I was trying to understand everything that launches in gazebo_launch, because I saw that there was also a ekf_node running, but I think I'm missing something...

Is there another launch only for simulation, or is it possible to use the same launch for simulation and real operation? Do I need to set up a tf broadcaster from /map to /base_link? Ask me any information you might need to solve this issue!

Have a nice day and thank you for your help!

**Comment by tonybaltovski** [comment]
Foxy is EOL and for ROS 2 Humble, this repository is no longer used. Please visit [clearpath_common](https://github.com/clearpathrobotics/clearpath_common). Check the [documentation](https://docs.clearpathrobotics.com/docs/ros/) for more details including supported sensors.
