### ISSUE TITLE
hsky_ur5_moveit gazebo inertial not stable

### ISSUE THREAD

**Issue by andrestoga** [husky/husky#25]
Hi,

I am simulating husky_ur5_moveit package in ROS indigo following this [tutorial](http://wiki.ros.org/husky_ur5_moveit_config/Tutorials/Husky%20UR5%20Mobile%20Manipulation%20Demo) but its inertial parameters are not stable. Whenever I start the simulation with the ur5 arm the husky always tips over as you can see in this [image](http://oi65.tinypic.com/25036u8.jpg).

I also tried to move the husky in its natural position (its four wheels on the ground) and then run the stow script to home the arm but then the husky again tipped over.

It is not the first time someone reported this behavior. As you can see [here](http://answers.ros.org/question/220411/hsky_ur5_moveit-gazebo-inertial-not-stable/)

Please let me know if you need more information.

I'm using the newest version.

Best,

**Comment by paulbovbel** [comment]
FYI @tonybaltovski sounds the Husky intertial params could use some tuning. 

@TheDash, did you see this when you were developing the moveit config/demos?

**Comment by andrestoga** [comment]
Hi,

I just fixed it by setting the parameter "laser_enabled" to false because I noticed that the sick laser was overlaid with the arm which was making the husky to tip over. The problem now is where to put the sick laser. In the [tutorial](http://wiki.ros.org/husky_ur5_moveit_config/Tutorials/Husky%20UR5%20Mobile%20Manipulation%20Demo) I can see that the sick laser is set below to the arm. Unfortunately, I don't now how to set the position of the sick laser in the URDF.

I'm also getting errors executing this command: 

roslaunch husky_ur5_moveit_config husky_ur5_planning_execution.launch sim:=true 

"[ERROR] [1459455461.302041689]: Semantic description is not specified for the same robot as the URDF" 

but it says that everything is ok: 

"All is well! Everyone is happy! You can start planning now!" 

and I also get the same error for this command: 

"roslaunch husky_ur5_moveit_config moveit_rviz.launch config:=true" 

"[ERROR] [1459455461.302041689]: Semantic description is not specified for the same robot as the URDF" 

And when I removed the sick laser I got the following error: 

[ERROR] [1459468059.912352351, 1680.830000000]: Link 'base_laser' is not known to URDF. Cannot disable collisons.

Best,

**Comment by paulbovbel** [comment]
One option for moving the laser around is via environment variables (http://wiki.ros.org/husky_bringup/Tutorials/Customize%20Husky%20Configuration#Environment_Variables)

I'll have to leave it with @TheDash to comment on the moveit configuration.

**Comment by CMobley7** [comment]
@andrestoga @paulbovbel @TheDash 

The inertial stability remains an issue for me in simulation. I adjusted the decorations.urdf.xacro to remove the front bumper and moved the lidar to its position in husky.urdf.xacro. As shown in the image below. In addition, I increased the husky's mass and proportionally the inertia in each direction. 

![new_lidar_location](https://cloud.githubusercontent.com/assets/10121829/16589082/8fbb5928-429f-11e6-9302-9e03d0f5e2ac.png)

While the robot spawns in the correct position now and stability overall improved, the husky turns right very slowly over time. In addition, any movement of the arm outside the bounds of the top_plate has a tendency to cause a lot of motion of the base. After observing the husky's behavior in simulation, I believe the issue could be caused by the ur5_arm_shoulder_lift_joint. As the majority of the motion occurred when the two link don't appear to be connected properly as in the image below. Any suggestion you can give on fixing this issue would be appreciated. 

![husky_ur5_inertia_issue](https://cloud.githubusercontent.com/assets/10121829/16589266/5ad4fed4-42a0-11e6-9d29-10819ae17942.png)

Thank you for your time and attention to this matter. Have a great week. God bless.

Very Respectfully,
CMobley7

**Comment by UltronDestroyer** [comment]
> The inertial stability remains an issue for me in simulation. I adjusted the decorations.urdf.xacro to remove the front bumper and moved the lidar to its position in husky.urdf.xacro. As shown in the image below. In addition, I increased the husky's mass and proportionally the inertia in each direction.

For best stability - I always just used laser_enabled:=false. However, that shouldn't have to be the case.

> > While the robot spawns in the correct position now and stability overall improved, the husky turns right very slowly over time. 

I've noticed this too.

> As the majority of the motion occurred when the two link don't appear to be connected properly as in the image below. Any suggestion you can give on fixing this issue would be appreciated.

I'll check what changing the position of the UR5 does. It looks like it may be too far off of the platform, causing all of this drifting and swaying.

**Comment by CMobley7** [comment]
@TheDash,

I measured the physical top_plate on our Husky and its dimensions were .825 m x .620 m x .006 m. However, the STL provided here has the top_plate dimensions as  .73 mm x .59 mm x 0.01 mm. I made a new top_plate with the physical dimensions above and exported it as an STL and DAE. I replaced the top_plate files in husky_description and expected to have to change the import size in the urdf. However, strangely it imported with the correct size. Now, the ur5_arm position match's on the physical and simulation Husky. However, the Husky now moves around erratically regardless of what is enabled. In an empty world, it will spawn as seen in the picture below and move around. I'm going to adjust my part later today from m to mm and see if this has any effect. Any additional ideas? Did changing the position of the ur5_arm in your urdf have any effect on the Husky's motions while the ur5_arm was moving?

![husky_with_new_top_plate](https://cloud.githubusercontent.com/assets/10121829/16880858/572116aa-4a85-11e6-96bf-7385601a2ac7.png)

**Comment by CMobley7** [comment]
@TheDash,

Adjusting it from m to mm fixed the erratic movement on startup. However, the adjusted plate dimensions had no effect on the stability that I can see. Any suggestions?

Thank you for your time and attention to this matter. Have a great weekend. God bless.

Very Respectfully,
CMobley7

**Comment by tonybaltovski** [comment]
Closing to due inactivity, please feel free to reopen if the needed.
