### ISSUE TITLE
Is it possible to integrate the ikfast with the ur5 in the Husky?

### ISSUE THREAD

**Issue by andrestoga** [husky/husky#26]
Hi,

I just want to ask if it is possible to integrate the ikfast plugin for Moveit! to the ur5 in the Husky following this [tutorial](http://docs.ros.org/hydro/api/moveit_ikfast/html/doc/ikfast_tutorial.html#moveit-ikfast-installation)?

Best,

**Comment by UltronDestroyer** [comment]
It should but it's not necessary. ROS Industrial has made a UR5 custom plugin that makes it plan very fast.
