### ISSUE TITLE
No `husky_node` in ROS 2 branches

### ISSUE THREAD

**Issue by IamPhytan** [husky/husky#276]
**Describe the feature you would like**

Hello, it seems like `husky_node` is not implemented on `ROS 2` branches.

This node was important as it used to publish `HuskyStatus` messages that could be used to monitor a Husky's energy consumption.
Is there a plan to migrate this node to ROS 2 ?

Thanks

**Comment by tonybaltovski** [comment]
This is indeed missing.  Are you just looking for that message or the diagnostics as well?

**Comment by IamPhytan** [comment]
I am looking for the message / to record real-time consumption data for research

**Comment by tonybaltovski** [comment]
Thanks for reporting this, we are working on adding this feature.

**Comment by tonybaltovski** [comment]
@IamPhytan #284 adds this.

**Comment by IamPhytan** [comment]
Thanks a lot !
