### ISSUE TITLE
Vizualizing husky in Rviz from remote computer

### ISSUE THREAD

**Issue by orjano-max** [husky/husky#279]
**Please provide the following information:**
 - OS: Jetpack 5.0.2, Nvidia AGX Xavier
 - ROS Distro: Galactic
 - Built from source or installed: built from source
 - Real hardware or simulation: real

 **Expected behaviour**
I am running a clearpath husky with packages built from source on an xavier. I can launch the husky on the xavier and everything works fine.

I want to be able to view the RobotModel on rviz on my remote computer. Usually i am launching the husky through ssh.
 
 **Actual behaviour**
 I can bring up rviz2 and view the robot model by selecting RobotModel and using "robot_description" as description topic.
However, when trying to view the robot on my remote computer, i add "RobotModel" in rviz and set "robot_description" as description topic. The robot model seems fine in rviz2  on the toolbar, but nothing shows up in the workspace.
I get this output to the terminal, but for all the links:
```bash
[ERROR] [1678715871.373767837] [rviz2]: could not load model 'file:///home/husky/Git/ORJANOS_MASTER_REPO/install/husky_description/share/husky_description/meshes/user_rail.dae' for link 'user_rail_link': FileNotFoundException: Cannot locate resource file:///home/husky/Git/ORJANOS_MASTER_REPO/install/husky_description/share/husky_description/meshes/user_rail.dae in resource group OgreAutodetect. in ResourceGroupManager::openResource at /tmp/binarydeb/ros-galactic-rviz-ogre-vendor-8.5.2/.obj-x86_64-linux-gnu/ogre-v1.12.1-prefix/src/ogre-v1.12.1/OgreMain/src/OgreResourceGroupManager.cpp (line 703)
```

From the message above, it seems to try to open the file from the local xavier. Btw. meshes is added to the share folder. I want to emphasize that this works fine when trying to view the robot locally on the husky.

Is it possible to get the model to show up when using rviz2 on a remote computer. I have sourced the packages before launching rviz2 so the "husky_description" package should be available on the remote computer.

**Comment by tonybaltovski** [comment]
Can you try this [branch](https://github.com/husky/husky/tree/mesh-fix)?  Also, we aren't really supporting Galactic, especially since it is EOL.

**Comment by orjano-max** [comment]
Yes i know galactic is eol, but sadly, i cannot use humble as Xavier does not support ubuntu 22 yet. And i would rather use Foxy, but due to compatibility issues with an interbotix vx300 robotic arm and Foxy, i will have to stick to galactic.
I am thankful for the help even though galactic is eol.

It seems that the branch is not building. From the error message, it seems like there is something wrong this the call to CallBackReturn. Is this function different from the one it has inherited from? Because i did actually use this call for CallBackReturn in the source code from the galactic branch:  `rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn`. I should probably have reported this bug earlier too but i don't really know if my quickfix is sufficient.

cloned git repo
sourced ros galactic
rosdep install --from-path src --ignore-src --rosdistro galactic -y
colcon build
got this build error:

```bash
--- stderr: husky_base                              
In file included from /home/orjan/husky_mes_fix_ws/src/husky/husky_base/src/husky_hardware.cpp:32:
/home/orjan/husky_mes_fix_ws/src/husky/husky_base/include/husky_base/husky_hardware.hpp:32:23: error: ‘CallbackReturn’ in namespace ‘hardware_interface’ does not name a type
   32 |   hardware_interface::CallbackReturn on_init(const hardware_interface::HardwareInfo & info) override;
      |                       ^~~~~~~~~~~~~~
/home/orjan/husky_mes_fix_ws/src/husky/husky_base/include/husky_base/husky_hardware.hpp:41:23: error: ‘CallbackReturn’ in namespace ‘hardware_interface’ does not name a type
   41 |   hardware_interface::CallbackReturn on_activate(const rclcpp_lifecycle::State & previous_state) override;
      |                       ^~~~~~~~~~~~~~
/home/orjan/husky_mes_fix_ws/src/husky/husky_base/include/husky_base/husky_hardware.hpp:44:23: error: ‘CallbackReturn’ in namespace ‘hardware_interface’ does not name a type
   44 |   hardware_interface::CallbackReturn on_deactivate(const rclcpp_lifecycle::State & previous_state) override;
      |                       ^~~~~~~~~~~~~~
/home/orjan/husky_mes_fix_ws/src/husky/husky_base/src/husky_hardware.cpp:194:21: error: ‘CallbackReturn’ in namespace ‘hardware_interface’ does not name a type
  194 | hardware_interface::CallbackReturn HuskyHardware::on_init(const hardware_interface::HardwareInfo & info)
      |                     ^~~~~~~~~~~~~~
/home/orjan/husky_mes_fix_ws/src/husky/husky_base/src/husky_hardware.cpp:313:21: error: ‘CallbackReturn’ in namespace ‘hardware_interface’ does not name a type
  313 | hardware_interface::CallbackReturn HuskyHardware::on_activate(const rclcpp_lifecycle::State & /*previous_state*/)
      |                     ^~~~~~~~~~~~~~
/home/orjan/husky_mes_fix_ws/src/husky/husky_base/src/husky_hardware.cpp:332:21: error: ‘CallbackReturn’ in namespace ‘hardware_interface’ does not name a type
  332 | hardware_interface::CallbackReturn HuskyHardware::on_deactivate(const rclcpp_lifecycle::State & /*previous_state*/)
      |                     ^~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/husky_hardware.dir/build.make:63: CMakeFiles/husky_hardware.dir/src/husky_hardware.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/husky_hardware.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
---
Failed   <<< husky_base [7.13s, exited with code 2]
```

**Comment by tonybaltovski** [comment]
How did you have it build before?  Can you cherry-pick https://github.com/husky/husky/commit/e7693cba9e2a5b55c298e7fa0a9c2230e95a40f2?

**Comment by orjano-max** [comment]
I actually copied the packages from the galactic branch to my own repo and did some changes described in my issue [here](https://github.com/orjano-max/ORJANOS_MASTER_REPO/issues/9).

I have added the fix from your commit to the files in my own repo [here](https://github.com/orjano-max/ORJANOS_MASTER_REPO/tree/galactic/code/src). I will test it tomorrow when i have access to the hardware and report back to you.

**Comment by orjano-max** [comment]
It worked! Changing to package path fixed the issue regarding viewing the robot on the remote computer!
However, it seems like there are some issues with gazebo regarding using the package path. Maybe a solution wold be to have the path as file path if gazebo sim is launched.

Also, as i said, i have done some modifications to the `husky_base` in order to get them to build on galactic. I am not sure if it is sufficient but it seems to work well. I have also added `interactive_marker_twist_server` to my [repo](https://github.com/orjano-max/ORJANOS_MASTER_REPO/tree/galactic/code/src) in order to use similar teleop packages as those used for foxy and humble. It is therefore large changes in the `husky_control` package related to this teleop modification.

Anyways, thanks for the help!

**Comment by orjano-max** [comment]
Just a quick update, i forked the galactic branch and committed some changes to `husky_base`, `husky_description` and `husky_control`. This is the repo: [uia_master_husky](https://github.com/orjano-max/uia_master_husky).

**Changes**

- Changes to `husky_base` source code in order to make it build on `galactic` [9a98b37](https://github.com/orjano-max/uia_master_husky/commit/9a98b3792485946da4da0ff857bce88a48815e84).
- Added the functionality in the urdf files of `husky_description` to change the path between file path and package path based on the variable "is_sim". This seems to remove the bugs regarding remote rviz and gazebo [707e5d5](https://github.com/orjano-max/uia_master_husky/commit/707e5d5f5f17f6c96c861ba2ad634586f8e832db).
- Added `interactive_marker_twist_server` [f9a510e](https://github.com/orjano-max/uia_master_husky/commit/f9a510e1df7a6db1ac8ea97e51810ba00990b317).
- Modded the launch file in `husky_base` in order to also launch teleop stuff and account for the changes in `husky_control,` as the default launch file brings up the husky but no teleop and twist_mux nodes. It also takes in a few more arguments in order to be more configurable [ed2623c](https://github.com/orjano-max/uia_master_husky/commit/ed2623cfdcc2a8d128ece11033922a8c7fd7aed7).
- Modded `husky_control` to look more similar to the foxy and humble packages [ed2623c](https://github.com/orjano-max/uia_master_husky/commit/ed2623cfdcc2a8d128ece11033922a8c7fd7aed7) and [19c9bc0](https://github.com/orjano-max/uia_master_husky/commit/19c9bc08d18a601532793e297ee5245dcda1710a).

Took the liberty to remove top plate and relocate `imu_link` to better fit actual husky at University of Agder. This is four lines of code in the beginning of [base_launch.py](https://github.com/orjano-max/uia_master_husky/blob/galactic-devel/husky_base/launch/base_launch.py):
```python
import os
```
and 
```python
os.environ["HUSKY_TOP_PLATE_ENABLED"] = "false"
os.environ["HUSKY_IMU_XYZ"] = "0 0 0"
os.environ["HUSKY_IMU_RPY"] = "0 0 0"
```
