### ISSUE TITLE
Cannot connect to wifi automatically!

### ISSUE THREAD

**Issue by Karin-Sugi** [husky/husky#294]
Hi, I am trying to connect my Husky to wifi network following the [youtube](https://www.youtube.com/watch?v=wA8UTF0mKBY) method using `wicd-curses`. However, after rebooting the Husky, it doesn't connect to wifi **automatically**... 
It works when I connect it **manually**. I mean when I connect my PC to Husky directly and press `Shift+C` in the `wicd-curses` manager, it is connected to the wifi network correctly. Thus, I'm sure password and SSID of the network are correct. 

Also, based on [this page](https://www.clearpathrobotics.com/assets/guides/noetic/husky/HuskyNetwork.html#connecting-to-wifi-access-point), I've checked `/etc/netplan/60-wireless.yaml`, which looks fine.

How can i fix it??

Thanks in advance.
Karin

**Comment by civerachb-cpr** [comment]
Github is not the ideal place to be debugging the robot's networking. The issues here should relate specifically to the robot's ROS packages.

Please contact our support team directly and they'll help you out: https://support.clearpathrobotics.com/hc/en-us/requests/new?ticket_form_id=59673
