### ISSUE TITLE
Resizing Husky Model in Gazebo

### ISSUE THREAD

**Issue by derektan95** [husky/husky#297]
Hi, 

**Describe the the feature you would like**
Is it possible to resize the husky model in gazebo (i.e. possibly via husky.urdf.xacro)? Naively setting the `scale` param within the `<mesh filename="package://husky_description/meshes/base_link.dae" scale="0.1 0.1 0.1" />` does not work. Thanks!

**Comment by civerachb-cpr** [comment]
The size of the Husky model is intended to accurately reflect the physical Husky robot (which only comes in one size).

Can I ask why you want to resize the model?

**Comment by derektan95** [comment]
Hi @civerachb-cpr,
I'm trying to do some simulation with the husky robot, but the world I'm tackling has very tight paths and corners. So I thought it would be nice to use the husky platform, but in a smaller size. Thanks!

**Comment by civerachb-cpr** [comment]
If you're looking for a similar robot to the Husky, but smaller, I would recommend trying the [Jackal](https://github.com/jackal/jackal). It has a very similar ROS interface, but is a much smaller platform.

_edit_
The Jackal code is split into a few repositories. The simulation data is here: https://github.com/jackal/jackal_simulator, but depends on the core description & control packages found in https://github.com/jackal/jackal.

**Comment by derektan95** [comment]
Hi @civerachb-cpr, 

Awesome idea. This will work well. Thanks!

**Comment by civerachb-cpr** [comment]
You're welcome! Glad to hear the Jackal will suit your needs.
