### ISSUE TITLE
Add husky status to humble branch

### ISSUE THREAD

**Issue by vinceHuyghe** [husky/husky#299]
Its seems this was merged into foxy devel in [248](https://github.com/husky/husky/pull/284) would it be possible to add this to the humble branch as well. Thanks

**Comment by tonybaltovski** [comment]
Hi @vinceHuyghe for Humble, the repository that should be used is https://github.com/clearpathrobotics/clearpath_common with  documentation here: https://docs.clearpathrobotics.com/docs/ros/

**Comment by vinceHuyghe** [comment]
Thank you
