### ISSUE TITLE
Voltage levels not showing

### ISSUE THREAD

**Issue by SOHAILMBS** [husky/husky#301]
**Please provide the following information:**
 - OS: Ubuntu 22.04 Jammy
 - ROS Distro: Humble
 - Built from source or installed: Source
 - Package version: Current version
 - Real hardware or simulation: Real hardware

 **Expected behaviour**
When doing **/diagnostics** expect to see battery level as well as motor current.

 **Actual behaviour**
Does not show either battery level or motor current.

**To Reproduce**

Run
```bash
ros2 topic echo /diagnostics
```

**Comment by tonybaltovski** [comment]
For ROS 2 Humble, this repository is no longer used. Please visit [clearpath_common](https://github.com/clearpathrobotics/clearpath_common). Check the [documentation](https://docs.clearpathrobotics.com/docs/ros/) for more details including supported sensors.  It should have the information on the `status` topic.

**Comment by SOHAILMBS** [comment]
Ah ok thank you will test it in our next Husky to see if it comes!
