### ISSUE TITLE
ROS2 humble navigation

### ISSUE THREAD

**Issue by er1c-cartman** [husky/husky#303]
Hi. I'm trying to run husky simulation with husky navigation, but currently, the package of navigation you've released for humble-devel doesn't seems to run it.
Is there any navigation package for husky navigation on ros2 humble?
Best regards

**Describe the the feature you would like**

**Other notes**
Add anything else you thing is important.

**Comment by tonybaltovski** [comment]
⚠️ For ROS 2 Humble, this repository is no longer used. Please visit [clearpath_common](https://github.com/clearpathrobotics/clearpath_common). Check the [documentation](https://docs.clearpathrobotics.com/docs/ros/) for more details including supported sensors.
