### ISSUE TITLE
FLIR PTU Bumblebee mounting bracket not part of model

### ISSUE THREAD

**Issue by wxmerkt** [husky/husky#38]
The mounting bracket connecting the Bumblebee2 to the PTU isn't part of the Dual Arm Husky URDF and the centre of rotation thus offset by the height of the bracket. Could you please add the bracket to the model/repository/URDF?

Thanks

Cf. https://github.com/husky/husky/tree/dual_ur5_husky/husky_description/meshes/accessories and https://github.com/husky/husky/tree/dual_ur5_husky/husky_description/meshes/

**Comment by wxmerkt** [comment]
Actually, self-observing with a camera mounted atop the rear end the whole mounting appears to be off, shifted for both the base of the PTU and the bracket for the bumblebee (this is after adding a 2cm offset for the bracket):

![screenshot-2016-12-03_16 56 02](https://cloud.githubusercontent.com/assets/1664508/20860830/91247c44-b979-11e6-80b0-4d15e4184478.png)

**Comment by wxmerkt** [comment]
It's off both in X and Y because the base_link has an offset from the mount_link due to the morphology of the PTU, cf:

![screenshot-2016-12-03_16 56 02](https://cloud.githubusercontent.com/assets/1664508/20860922/645cb31e-b97b-11e6-82c6-de283758db06.png)

![screenshot-2016-12-03_17 09 44](https://cloud.githubusercontent.com/assets/1664508/20860924/689d04f6-b97b-11e6-8767-9f5caaa883f0.png)

**Comment by wxmerkt** [comment]
I've proposed a partial fix to this in #39. There's an upstream issue to add the mounting bracket: https://github.com/ros-drivers/flir_ptu/issues/31

**Comment by tonybaltovski** [comment]
@wxmerkt @TheDash I am going to close this since it part of the Dual Arm Husky URDF.
