### ISSUE TITLE
Pull args from _description and _gazebo into header.xacro

### ISSUE THREAD

**Issue by paulbovbel** [husky/husky#5]
Pull args repeated in so many files:

<xacro:arg name="laser_enabled" default="false" />
<xacro:arg name="ur5_enabled" default="false" />
<xacro:arg name="kinect_enabled" default="false" />

Into a single xacro 'header' file.

**Comment by UltronDestroyer** [comment]
My proposed fix to end all of this nonsense:

Add a $(rosparam ur5_enabled) which searches the rosparam server for that variable.  In the launch file, the params can be set once for the robot and used once in the xacro.

Ofc a pull request will have to be made to xacro

**Comment by paulbovbel** [comment]
There would have to be a mechanism to guarantee thta all launch file params are loaded before the <param> call to load 'robot_description' via xacro call, which is why there's a distinction between <arg> and <param> in the first place.

**Comment by UltronDestroyer** [comment]
True, we would have to solve that as well.

**Comment by UltronDestroyer** [comment]
It's either we solve that, or have to do the exact same thing for the Jackal+UR3/MICO, the grizzly+UR10, and the LIRP.

Really just a choice of being smart or working hard IMHO.

**Comment by mikepurvis** [comment]
Not convinced this medicine is better than the disease. What about env
vars, like Jackal?

**Comment by UltronDestroyer** [comment]
envvars requires setting params on a bashrc. This is why I believe it is problematic: Why use a bashrc and not something more generic, like rosparam? For each system designed, there will have to be an install sequence that modifies the bashrc for each platform it goes onto. 

In addition, for multi-robot/multi-master/multi-machine, these parameters can't be queried over a network. So launching nodes on two different machines would require having the same bashrc config on each machine. 

The bashrc stuff cannot be dynamically modified in a way that it looks neat. Everything on the systems we're using has access to the param server, whereas only C++/programming languages/scripts can modify the bashrc.

The costs I forsee of implementing a rosparam server to give us these params are:
same usage as optev, but replace optenv with $(rosparam param-name default-value).  

Paul brought up an issue of ensuring that the params are set before their usage, I'm not a multi-threading/process engineer so I can't comment on that, but I understand enough to see that if machine A brings up a node and modifies a rosparam, and machine B brings up the same file but modifies the same rosparam, A might receive B's value. Which, I don't know how rosparam serv handles that but would be worth looking into.

**Comment by mikepurvis** [comment]
Note that both [ros-system-daemon](https://github.com/TurtleBot-Mfg/ros-system-daemon-hydro/blob/4166da41d728f602ebd8ef4a613b5decdcbdb37f/root/usr/sbin/rosctl#L55) and [robot_upstart](https://github.com/clearpathrobotics/robot_upstart/blob/4bd921bd9f8202a00dc5b877891c81dd3cf47642/templates/job-start.em#L36) both explicitly support a scheme for injecting environment variables into the startup launch sequence. On CPR platforms, we insert them into a standard location: `/etc/ros/setup.bash`. No `.bashrc` modifications necessary.

Let's discuss the various pros and cons further at the meeting next week.

**Comment by paulbovbel** [comment]
arg processed before include in xacro, not feasible
