### ISSUE TITLE
cannot find multimaster_launch

### ISSUE THREAD

**Issue by yinzixuan126** [husky/husky#52]
I couldn't find multimaster_launch package when i launched husky empty world launch.

After search on google and ros wiki , i found one package named multimaster, but  it doesn't seem like the right one. http://wiki.ros.org/multimaster

**Comment by tonybaltovski** [comment]
Which distro are you testing this on?

**Comment by yinzixuan126** [comment]
sorry for ignoring branch level. I am using indigo version.
