### ISSUE TITLE
Visual servoing with husky-ur5 ???

### ISSUE THREAD

**Issue by Abduoit** [husky/husky#72]
Hi
I have husky-ur5 robot, I am able to control the arm and mobile robot by Moviet and rviz, but I still need to control the ur5 based on the movement of my real hand (i.e object tracking with depth sensor)

Anyone can help me how to do object tracking with ur5 arm ???

**Comment by majcote** [comment]
Hello!

Great questions! Unfortunately this isn't quite the correct place for it, that's not something that we can inherently support. Your best bet would be to ask the  ROS answers community, (https://answers.ros.org/questions/)  there's usually plenty of ROS experts there that will be willing to help, and often even many of our own developers.

Best of luck!
