### ISSUE TITLE
UR5 support on kinetic-devel

### ISSUE THREAD

**Issue by luiscarlosfeliz** [husky/husky#75]
I've noticed some changes from indigo to kinetic devel, like the UR5 argument that disappeared form the description file. Is it possible to launch the ur5 manipulator with the kinetic version?

**Comment by tonybaltovski** [comment]
We are in the process of moving out the manipulator packages from the core Husky packages to [here](https://github.com/husky/husky_manipulation).  They have only been tested for Indigo so far.

**Comment by tonybaltovski** [comment]
Closing to due inactivity, please feel free to reopen if the needed.
