### ISSUE TITLE
amcl doesnot avoid obstacles actively

### ISSUE THREAD

**Issue by hoppss** [husky/husky#83]
Hi, 

Now amcl will not avoid obstacles if there are new obstacle in the workspace that does not log in gmapping maps.

How should we modify this pkg ?

**Comment by tonybaltovski** [comment]
@hoppss can you give more details about what you are using?  (ie real vs sim)  Also, are you using indigo or kinetic?  I see to explicit issues with this on the navigation repo.

**Comment by hoppss** [comment]
Hi ,
sorry. 
We bought both  husky and jackal . I found jackal ( not husky, sorry) didnot avoid obstacles when i run jackal repo 's  navigation package  with a map that i made by gmapping.
It looks like the local planner doesnot work.

**Comment by tonybaltovski** [comment]
@hoppss are the laser's frame and topic correct?

**Comment by hoppss** [comment]
@tonybaltovski you are right!
Thank you very much. May you have a good day.

**Comment by tonybaltovski** [comment]
@hoppss was this integrated by us?

**Comment by hoppss** [comment]
no.
It is well to simulation with jackal gazebo model.
I clone it to my pc to run it with a real jackal, I didnot modify the frame parameters completely.

**Comment by dniewinski** [comment]
@hoppss Glad to hear everything is working.  Closing the ticket
