### ISSUE TITLE
g-mapping demo (purple overlay)

### ISSUE THREAD

**Issue by aarontan-git** [husky/husky#84]
Hello,

I am running Ubuntu 16.04 + ROS Kinetic.

When I run the husky gmapping demo, I get this purple overlay in rviz (see attached image). I have ran the same demo in ROS Indigo with Ubuntu 14.04 and there wasn't any purple overlay.

Can someone explain what this is? How do I get rid of it?

![gmapping](https://user-images.githubusercontent.com/35575286/40144086-5fbb0896-592b-11e8-9838-96cf9ae26921.png)

Thanks,
Aaron

**Comment by dniewinski** [comment]
Good morning Aaron.  That large purple bubble is showing the positional covariance of the robot's odometry.  This bubble was added in Kinetic.  To turn it off in RViz, under Displays, expand Sensing > Odometry > Covariance.  You can un-check Position and it will stop showing up, or you can change the alpha or colour so it is less noticeable
