### ISSUE TITLE
AMCL Demo Pose Estimate?

### ISSUE THREAD

**Issue by aarontan-git** [husky/husky#85]
Hello,

I have a question about the initiation process of the AMCL Demo.
In the tutorial, it mentions to do: "Use the 2D Pose Estimate tool in the top toolbar to give amcl an initial pose estimate. Without an initial estimate, the Monte Carlo localization approach is unlikely to converge the correct pose. "

I am wondering, for simulation - is this as simple as using the 2D Pose Estimate arrow and select the husky's initial location in RVIZ and point the arrow in the direction of the heading angle? How does this process work for physical experimentation?

Thank you,
Aaron

**Comment by tonybaltovski** [comment]
@aarontan94, it is the same process for the real robot, the AMCL demo is platform agnostic.

**Comment by aarontan-git** [comment]
@tonybaltovski I am more wondering about the specifics. How do I actually use the 2D pose estimate tool? Is it as I described?

**Comment by tonybaltovski** [comment]
@aarontan94 Yup, just like that. By clicking the `rviz/SetInitialPose` you are publishing to AMCL's `initialpose` topic. (for reference: http://wiki.ros.org/amcl?distro=kinetic)

**Comment by aarontan-git** [comment]
@tonybaltovski thank you!
