### ISSUE TITLE
Problem launching simulation

### ISSUE THREAD

**Issue by tiberium24** [husky/husky#86]
After catkin making and trying to run this roslaunch husky_gazebo husky_empty_world.launch

i get the following error:

while processing /home/john/husky_indigo_ws/src/husky/husky_control/launch/control.launch:
Invalid <arg> tag: Invalid left parenthesis '(' in substitution args [$(eval optenv('HUSKY_CONFIG_EXTRAS', find('husky_control') + '/config/empty.yaml'))].

Can you check if the latest version works or what else is the issue here?

**Comment by tonybaltovski** [comment]
Hey @Ioannisvt, I noticed that have an Indigo workspace. That error would come code in the kinetic branch,  are you on the indigo-devel branch?

**Comment by tiberium24** [comment]
You are right, I didn't notice in my hurry, thank you!

**Comment by tonybaltovski** [comment]
No worries!
