### ISSUE TITLE
How to access sensor's measurement values?

### ISSUE THREAD

**Issue by tiberium24** [husky/husky#96]
I believe that by odometry_filtered i am accessing only the corrected values. I also want to have access to the measured ones from GPS, etc. Is that possible and how/where?
Thank you

**Comment by tiberium24** [comment]
Having the fused values is what i want actually.

**Comment by tonybaltovski** [comment]
Hello!

Great questions! Unfortunately this isn't quite the correct place for it, that's not something that we can inherently support. Your best bet would be to ask the ROS answers community, (https://answers.ros.org/questions/) there's usually plenty of ROS experts there that will be willing to help.

Best of luck!
